#!/usr/bin/env bash
# Refresh core tools and GitHub Actions from upstream releases and open one PR.
#
# Intended to run from CI (update-tools workflow) with a GitHub token that has
# contents:write, pull-requests:write, and statuses:write. Exits 0 when
# nothing changed.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

BRANCH="automation/dependency-updates"

# shellcheck source=scripts/lib/github-pr.sh
source "$ROOT/scripts/lib/github-pr.sh"

push_update_branch() {
  push_automation_branch "$BRANCH"
}

ensure_update_pull_request() {
  ensure_automation_pull_request "$BRANCH" "$1" "$2"
}

validate_update_branch() {
  local head_sha run_id="" attempt

  head_sha="$(git rev-parse HEAD)"
  gh workflow run validate.yml --ref "$BRANCH"

  for attempt in {1..12}; do
    runs="$(gh run list --workflow validate.yml --branch "$BRANCH" \
      --event workflow_dispatch --limit 10 --json databaseId,headSha \
      --jq '.[] | select(.headSha == "'"$head_sha"'") | .databaseId')" \
      || continue
    run_id="${runs%%$'\n'*}"
    [ -n "$run_id" ] && break
    echo "waiting for dispatched validation run (${attempt}/12)"
    sleep 5
  done

  if [ -z "$run_id" ]; then
    echo "dispatched validation run was not found for ${head_sha}" >&2
    return 1
  fi

  echo "waiting for validation run ${run_id} on ${BRANCH}"
  gh run watch "$run_id" --exit-status
}

# Bind the automerge gate to this exact commit: automerge.yml merges only a
# head SHA carrying a successful "dependency-update-validation" status, so a
# later push to the branch can never ride an older commit's validation.
record_validation_status() {
  local head_sha repository status_output

  head_sha="$(git rev-parse HEAD)"
  repository="${GITHUB_REPOSITORY:-KuGouGo/Rules}"
  if status_output="$(gh api --method POST \
    "repos/${repository}/statuses/${head_sha}" \
    -f state=success \
    -f context="dependency-update-validation" \
    -f description="Validated dependency update branch" \
    -f target_url="${GITHUB_SERVER_URL:-https://github.com}/${repository}/actions/runs/${GITHUB_RUN_ID:-}" \
    2>&1)"; then
    echo "recorded dependency-update-validation status on ${head_sha}"
  else
    # Without the status the automerge workflow refuses to merge, so a failed
    # status write must fail the run loudly instead of leaving a stale PR.
    printf 'failed to record validation status on %s: %s\n' "$head_sha" "$status_output" >&2
    return 1
  fi
}

main() {
  local tool_output action_output versions title body

  cd "$ROOT"
  tool_output="$(python3 "$ROOT/scripts/tools/update-tool-lock.py" --root "$ROOT")"
  action_output="$(python3 "$ROOT/scripts/tools/update-action-pins.py" --root "$ROOT")"
  printf '%s\n' "$tool_output"
  printf '%s\n' "$action_output"

  if ! grep -q '^changed=true$' <<< "$tool_output" &&
    ! grep -q '^changed=true$' <<< "$action_output"; then
    echo "no dependency updates available"
    return 0
  fi

  # Validate the refreshed release binaries before proposing them: verify
  # archive + binary digests and version probes, run the full test suite, and
  # compile deterministic custom artifacts with both tools.
  # shellcheck source=scripts/lib/common.sh
  source "$ROOT/scripts/lib/common.sh"
  setup_tool_cache
  ensure_sing_box
  ensure_mihomo
  # Regenerate the binary goldens with the refreshed compilers so the golden
  # fixture test validates against the new locked versions in this same PR.
  bash "$ROOT/scripts/commands/update-binary-goldens.sh"
  REQUIRE_SHELLCHECK=1 make validate-tool-update

  versions="$(printf '%s\n%s\n' "$tool_output" "$action_output" |
    sed -n 's/^versions=//p' | paste -sd '|' - | sed 's/|/, /g')"
  [ -n "$versions" ] || versions="dependencies"
  title="chore: update dependencies (${versions})"

  git config user.name "github-actions[bot]"
  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
  git checkout -B "$BRANCH"
  git add config/tools-lock.json .github/actions .github/workflows \
    scripts/tests/test-tool-lock.sh scripts/tests/test-upstream-config.sh \
    scripts/tests/fixtures/binary
  git commit -m "${title}" -m "Auto-generated by the update-tool-versions workflow.

Digests and tag commits were computed from the upstream release assets. The
refreshed lock was validated locally (archive + binary SHA-256 checks and
version probes) before this branch was created."

  body="Auto-generated by the update-tool-versions workflow.

Updated dependencies: ${versions}.

The refreshed lock was validated (archive + binary SHA-256 checks and version
probes) before this branch was created."
  push_update_branch
  ensure_update_pull_request "$title" "$body"
  validate_update_branch
  record_validation_status
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
