#!/usr/bin/env bash

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

BRANCH="automation/dependency-updates"
VALIDATION_CONTEXT="dependency-update-validation"

# shellcheck source=scripts/lib/github-pr.sh
source "$ROOT/scripts/lib/github-pr.sh"

push_update_branch() {
  push_automation_branch "$BRANCH"
}

ensure_update_pull_request() {
  ensure_automation_pull_request "$BRANCH" "$1" "$2"
}

main() {
  local tool_output action_output versions title body

  cd "$ROOT"
  tool_output="$(python3 "$ROOT/scripts/tools/update-tool-lock.py" --root "$ROOT")"
  action_output="$(python3 "$ROOT/scripts/tools/update-action-pins.py" --root "$ROOT")"
  printf '%s\n' "$tool_output"
  printf '%s\n' "$action_output"

  if ! grep -q '^changed=true$' <<< "$tool_output" &&
    ! grep -q '^changed=true$' <<< "$action_output"; then
    echo "no dependency updates available"
    return 0
  fi

  # shellcheck source=scripts/lib/common.sh
  source "$ROOT/scripts/lib/common.sh"
  setup_tool_cache
  ensure_sing_box
  ensure_mihomo

  bash "$ROOT/scripts/commands/update-binary-goldens.sh"
  REQUIRE_SHELLCHECK=1 make validate-tool-update

  versions="$(printf '%s\n%s\n' "$tool_output" "$action_output" |
    sed -n 's/^versions=//p' | paste -sd '|' - | sed 's/|/, /g')"
  [ -n "$versions" ] || versions="dependencies"
  title="chore: update dependencies (${versions})"

  git config user.name "github-actions[bot]"
  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
  git checkout -B "$BRANCH"
  git add config/tools-lock.json .github/actions .github/workflows \
    scripts/tests/test-tool-lock.sh scripts/tests/test-upstream-config.sh \
    scripts/tests/fixtures/binary
  git commit -m "${title}" -m "Auto-generated by the update-tool-versions workflow.

Digests and tag commits were computed from the upstream release assets. The
refreshed lock was validated locally (archive + binary SHA-256 checks and
version probes) before this branch was created."

  body="Auto-generated by the update-tool-versions workflow.

Updated dependencies: ${versions}.

The refreshed lock was validated (archive + binary SHA-256 checks and version
probes) before this branch was created."
  push_update_branch
  ensure_update_pull_request "$title" "$body"
  validate_automation_branch "$BRANCH"
  record_validation_status "$VALIDATION_CONTEXT" "Validated dependency update branch"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
