#!/usr/bin/env bash
# Refresh config/tools-lock.json from upstream releases and open a PR.
#
# Intended to run from CI (update-tools workflow) with a GitHub token that has
# contents:write and pull-requests:write. Exits 0 when nothing changed.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

BRANCH="chore/update-tool-versions"

output="$(python3 "$ROOT/scripts/tools/update-tool-lock.py" --root "$ROOT")"
printf '%s\n' "$output"

if ! grep -q '^changed=true$' <<< "$output"; then
  echo "no tool version updates available"
  exit 0
fi

# Validate the refreshed lock end-to-end before proposing it: download the new
# binaries and verify archive + binary digests and version probes, then run the
# full validation suite against the new lock.
# shellcheck source=scripts/lib/common.sh
source "$ROOT/scripts/lib/common.sh"
setup_tool_cache
ensure_sing_box
ensure_mihomo
REQUIRE_SHELLCHECK=1 make validate

versions="$(sed -n 's/^versions=//p' <<< "$output" | head -1)"
[ -n "$versions" ] || versions="tool versions"
title="chore: bump locked tool versions (${versions})"

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git checkout -b "$BRANCH"
git add config/tools-lock.json scripts/tests/test-tool-lock.sh scripts/tests/test-upstream-config.sh
git commit -m "${title}" -m "Auto-generated by the update-tool-versions workflow.

Digests and tag commits were computed from the upstream release assets. The
refreshed lock was validated locally (archive + binary SHA-256 checks and
version probes) before this branch was created."

if git ls-remote --exit-code origin "refs/heads/${BRANCH}" >/dev/null 2>&1; then
  git push -u --force-with-lease origin "$BRANCH"
else
  git push -u origin "$BRANCH"
fi

pr_number="$(gh pr list --head "$BRANCH" --state open --json number --jq '.[0].number // empty' 2>/dev/null || true)"
if [ -n "$pr_number" ]; then
  echo "pull request #${pr_number} already open for ${BRANCH}; branch updated"
else
  body="Auto-generated by the update-tool-versions workflow.

Updated locked versions: ${versions}.

The refreshed lock was validated (archive + binary SHA-256 checks and version
probes) before this branch was created."
  gh pr create --base main --head "$BRANCH" --title "$title" --body "$body"
fi
