#!/usr/bin/env bash
# Propose an upstream source pin bump as one pull request.
#
# Intended to run from CI (update-upstream-pins workflow). Reads the upstream
# remote HEAD recorded in config/upstreams.json, compares it against the pinned
# revision in config/upstream-pins.json, and opens a validated PR when they
# differ. Trusted automation merges that exact validated commit.
# Exits 0 when the pin is current.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

BRANCH="automation/upstream-pins"
VALIDATION_CONTEXT="upstream-pin-validation"

# shellcheck source=scripts/lib/github-pr.sh
source "$ROOT/scripts/lib/github-pr.sh"

validate_update_branch() {
  local head_sha run_id="" runs attempt

  head_sha="$(git rev-parse HEAD)"
  gh workflow run validate.yml --ref "$BRANCH"

  for attempt in {1..12}; do
    runs="$(gh run list --workflow validate.yml --branch "$BRANCH" \
      --event workflow_dispatch --limit 10 --json databaseId,headSha \
      --jq '.[] | select(.headSha == "'"$head_sha"'") | .databaseId')" \
      || continue
    run_id="${runs%%$'\n'*}"
    [ -n "$run_id" ] && break
    echo "waiting for dispatched validation run (${attempt}/12)"
    sleep 5
  done

  [ -n "$run_id" ] || {
    echo "dispatched validation run was not found for ${head_sha}" >&2
    return 1
  }
  echo "waiting for validation run ${run_id} on ${BRANCH}"
  gh run watch "$run_id" --exit-status
}

record_validation_status() {
  local head_sha repository

  head_sha="$(git rev-parse HEAD)"
  repository="${GITHUB_REPOSITORY:-KuGouGo/Rules}"
  gh api --method POST "repos/${repository}/statuses/${head_sha}" \
    -f state=success \
    -f context="$VALIDATION_CONTEXT" \
    -f description="Validated upstream pin update" \
    -f target_url="${GITHUB_SERVER_URL:-https://github.com}/${repository}/actions/runs/${GITHUB_RUN_ID:-}"
  echo "recorded ${VALIDATION_CONTEXT} status on ${head_sha}"
}

pin_value() {
  python3 - "$1" "$2" <<'PY'
import json
import sys

path, key = sys.argv[1:]
data = json.loads(open(path, encoding="utf-8").read())
pin = data.get("pins", {}).get(key, {})
print(pin.get("commit", ""))
PY
}

main() {
  cd "$ROOT"

  local dlc_url remote_head pinned
  dlc_url="$(python3 - <<'PY'
import json
print(json.load(open("config/upstreams.json", encoding="utf-8"))["domain"]["dlc"]["url"])
PY
)"
  remote_head="$(git ls-remote "$dlc_url" HEAD | awk 'NR == 1 { print $1 }')"
  [ -n "$remote_head" ] || { echo "could not resolve upstream HEAD for $dlc_url" >&2; return 1; }
  pinned="$(pin_value config/upstream-pins.json domain.dlc)"

  if [ "$remote_head" = "$pinned" ]; then
    echo "upstream pins up to date (${remote_head})"
    return 0
  fi

  echo "domain.dlc pin bump: ${pinned:-<none>} -> ${remote_head}"
  python3 - "config/upstream-pins.json" "$remote_head" <<'PY'
import json
import sys
from pathlib import Path

path, commit = sys.argv[1:]
data = json.loads(Path(path).read_text(encoding="utf-8"))
data["pins"]["domain.dlc"]["commit"] = commit
Path(path).write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
PY

  git config user.name "github-actions[bot]"
  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

  git checkout -B "$BRANCH"
  git add config/upstream-pins.json
  git commit -m "chore: pin domain-list-community to ${remote_head}" \
    -m "Auto-generated by the update-upstream-pins workflow. The build checks out
this pinned commit instead of the upstream moving master. The automation
validates this exact commit before merging it."

  push_automation_branch "$BRANCH"

  ensure_automation_pull_request "$BRANCH" \
    "chore: pin domain-list-community to ${remote_head}" \
    "Auto-generated by the update-upstream-pins workflow.

Updates the pinned \`domain-list-community\` commit from \`${pinned:-none}\` to \`${remote_head}\`.

The update workflow validates this exact commit before trusted automation
squash-merges it. The next scheduled build then consumes the new revision."
  validate_update_branch
  record_validation_status
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
