#!/usr/bin/env bash

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

BRANCH="automation/upstream-pins"
VALIDATION_CONTEXT="upstream-pin-validation"

# shellcheck source=scripts/lib/github-pr.sh
source "$ROOT/scripts/lib/github-pr.sh"

pin_value() {
  python3 - "$1" "$2" <<'PY'
import json
import sys

path, key = sys.argv[1:]
data = json.loads(open(path, encoding="utf-8").read())
pin = data.get("pins", {}).get(key, {})
print(pin.get("commit", ""))
PY
}

main() {
  cd "$ROOT"

  local dlc_url remote_head pinned
  dlc_url="$(python3 - <<'PY'
import json
print(json.load(open("config/upstreams.json", encoding="utf-8"))["domain"]["dlc"]["url"])
PY
)"
  remote_head="$(git ls-remote "$dlc_url" HEAD | awk 'NR == 1 { print $1 }')"
  [ -n "$remote_head" ] || { echo "could not resolve upstream HEAD for $dlc_url" >&2; return 1; }
  pinned="$(pin_value config/upstream-pins.json domain.dlc)"

  if [ "$remote_head" = "$pinned" ]; then
    echo "upstream pins up to date (${remote_head})"
    return 0
  fi

  echo "domain.dlc pin bump: ${pinned:-<none>} -> ${remote_head}"
  python3 - "config/upstream-pins.json" "$remote_head" <<'PY'
import json
import sys
from pathlib import Path

path, commit = sys.argv[1:]
data = json.loads(Path(path).read_text(encoding="utf-8"))
data["pins"]["domain.dlc"]["commit"] = commit
Path(path).write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
PY

  git config user.name "github-actions[bot]"
  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

  git checkout -B "$BRANCH"
  git add config/upstream-pins.json
  git commit -m "chore: pin domain-list-community to ${remote_head}" \
    -m "Auto-generated by the update-upstream-pins workflow. The build checks out
this pinned commit instead of the upstream moving master. The automation
validates this exact commit before merging it."

  push_automation_branch "$BRANCH"

  ensure_automation_pull_request "$BRANCH" \
    "chore: pin domain-list-community to ${remote_head}" \
    "Auto-generated by the update-upstream-pins workflow.

Updates the pinned \`domain-list-community\` commit from \`${pinned:-none}\` to \`${remote_head}\`.

The update workflow validates this exact commit before trusted automation
squash-merges it. The next scheduled build then consumes the new revision."
  validate_automation_branch "$BRANCH"
  record_validation_status "$VALIDATION_CONTEXT" "Validated upstream pin update"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
