name: Rules Converter

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  convert-rules:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: src
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip jq
          pip3 install pyyaml
          latest_url=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r '.assets[] | select(.name | test("mihomo-linux-amd64.*.gz$")) | .browser_download_url')
          curl -sfL "$latest_url" | gzip -d > mihomo
          chmod +x mihomo && sudo mv mihomo /usr/local/bin/
          mkdir -p src/{ipcidr,domain}

      - name: Process Rules
        run: |
          cd src

          download_and_process() {
            local rule="$1"
            local url="$2"
            echo "🔄 Processing: $rule"

            if ! curl -sfL -o "${rule}.origin" "$url"; then
              echo "::error::Download failed: $url"
              exit 1
            fi

            if [[ "$url" == *.yaml ]]; then
              python3 -c "import yaml,sys; print('\n'.join(yaml.safe_load(open('${rule}.origin'))['payload']))" > "${rule}.tmp"
              rm "${rule}.origin"
            else
              mv "${rule}.origin" "${rule}.tmp"
            fi

            if [[ "$rule" == ipcidr/* ]]; then
              mihomo convert-ruleset ipcidr text "${rule}.tmp" "${rule}.mrs"
            else
              sed -i '
                /^[[:space:]]*$/d;
                s/^full://g;
                s/^DOMAIN-SUFFIX,//g;
                s/^DOMAIN,//g;
              ' "${rule}.tmp"

              awk '!seen[tolower($0)]++' "${rule}.tmp" | sort -f > "${rule}.processed"
              mihomo convert-ruleset domain text "${rule}.processed" "${rule}.mrs"
            fi

            rm -f "${rule}.tmp" "${rule}.processed"
          }

          declare -A RULES=(
            ["domain/ai"]="https://github.com/DustinWin/ruleset_geodata/raw/mihomo-ruleset/ai.list"
            ["domain/cn"]="https://github.com/DustinWin/ruleset_geodata/raw/mihomo-ruleset/cn.list"
            ["domain/fake_ip"]="https://github.com/juewuy/ShellCrash/raw/dev/public/fake_ip_filter.list"
            ["domain/private"]="https://github.com/ForestL18/rules-dat/raw/mihomo/geo/domain/private-domain.list"
            ["domain/paypal"]="https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/paypal.yaml"
            ["ipcidr/privateip"]="https://github.com/ForestL18/rules-dat/raw/mihomo/geo/ipcidr/private-ip.list"
            ["ipcidr/cnip"]="https://github.com/ForestL18/rules-dat/raw/mihomo/asn/combined/China-ASN-combined.list"
            ["ipcidr/telegramip"]="https://github.com/ForestL18/rules-dat/raw/mihomo/asn/combined/Telegram-ASN-combined.list"
            ["ipcidr/googleip"]="https://github.com/ForestL18/rules-dat/raw/mihomo/asn/combined/Google-ASN-combined.list"
          )

          for rule in "${!RULES[@]}"; do
            download_and_process "$rule" "${RULES[$rule]}"
          done

      - name: Commit Changes
        run: |
          cd src
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ipcidr/*.mrs domain/*.mrs
          if ! git diff-index --quiet HEAD; then
            git commit -m "chore: Update rules $(date +'%Y-%m-%d %H:%M')" 
            git push origin HEAD:${{ github.ref }}
          fi
