name: Rules Converter

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点自动运行

jobs:
  convert-rules:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write  # 授予写入权限

    steps:
      # 步骤 1: 检出仓库
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: src
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      # 步骤 2: 安装指定版本 Mihomo
      - name: Setup Mihomo
        run: |
          cd src
          
          # 使用您提供的下载链接
          MI_URL="https://github.com/MetaCubeX/mihomo/releases/download/v1.19.3/mihomo-linux-amd64-v1.19.3.gz"
          
          # 下载并解压
          curl -sL $MI_URL | gzip -d > mihomo
          
          # 验证并安装
          chmod +x mihomo
          sudo mv mihomo /usr/local/bin/
          mihomo -v  # 验证版本

      # 步骤 3: 下载并处理 CDN 规则文件
      - name: Process CDN Rules
        run: |
          cd src
          # 下载原始规则文件
          curl -sL "https://github.com/pmkol/easymosdns/raw/rules/cdn_domain_list.txt" -o raw.txt
          
          # 优化规则筛选条件
          grep -vE '^(#|$)' raw.txt |  # 移除注释和空行
          sed 's/^\*\.//g' |           # 移除通配符前缀
          sed 's/^full://g' |          # 移除 "full:" 前缀
          awk '!seen[tolower($0)]++' | # 不区分大小写去重
          grep -E '^[a-zA-Z0-9.-]+$' | # 仅保留合法域名
          sort -f |                    # 不区分大小写排序
          awk '{print "DOMAIN-SUFFIX,"$0}' > cdn.list  # 生成规则格式
          
          # 添加文件头
          echo -e "# CDN Domain List\n# Updated: $(date -u +'%Y-%m-%dT%H:%M:%SZ')\n# Total: $(grep -c 'DOMAIN-SUFFIX' cdn.list) rules" | cat - cdn.list > temp && mv temp cdn.list
          mihomo convert-ruleset domain text cdn.list cdn.mrs
      # 步骤 4: 下载并处理 Emby 规则文件
      - name: Process Emby Rules
        run: |
          cd src
          # 下载 Emby 规则文件
          curl -sL "https://github.com/KuGouGo/Rules/raw/refs/heads/main/emby.list" -o emby.list
          
          # 转换 Emby 规则
          mihomo convert-ruleset domain text emby.list emby.mrs

      # 步骤 5: 下载并处理 ake_ip_filter 规则文件
      - name: Process fake_ip_filter Rules
        run: |
          cd src
          # 下载 fake_ip_filter 规则文件
          curl -sL "https://raw.githubusercontent.com/juewuy/ShellCrash/dev/public/fake_ip_filter.list" -o fake_ip_filter.list
          
          # 转换 fake_ip_filter 规则
          mihomo convert-ruleset domain text fake_ip_filter.list fake_ip_filter.mrs

      # 步骤 6: 提交变更
      - name: Commit Changes
        run: |
          cd src
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add cdn.list cdn.mrs emby.list emby.mrs
          
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Update: $(date +'%Y-%m-%d')"
            git push origin HEAD:${{ github.ref }}
          fi
