name: Rules Converter

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' 

jobs:
  convert-rules:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: src
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Setup Environment
        run: |
          cd src
          mkdir -p {ipcidr,domain}  # 创建分类目录
          
          # 安装 Mihomo
          curl -sfL "https://github.com/MetaCubeX/mihomo/releases/download/v1.19.3/mihomo-linux-amd64-v1.19.3.gz" | gzip -d > mihomo
          chmod +x mihomo && sudo mv mihomo /usr/local/bin/

      - name: Process Rules
        run: |
          cd src
          
          declare -A RULES=(
            # Domain Rules
            ["domain/cdn"]="https://github.com/pmkol/easymosdns/raw/rules/cdn_domain_list.txt"
            ["domain/ai"]="https://github.com/DustinWin/ruleset_geodata/raw/mihomo-ruleset/ai.list"
            ["domain/cn"]="https://github.com/DustinWin/ruleset_geodata/raw/mihomo-ruleset/cn.list"
            ["domain/fake_ip"]="https://github.com/juewuy/ShellCrash/raw/dev/public/fake_ip_filter.list"
            ["domain/private"]="https://github.com/ForestL18/rules-dat/raw/mihomo/geo/domain/private-domain.list"
            
            # IPCIDR Rules
            ["ipcidr/privateip"]="https://github.com/ForestL18/rules-dat/raw/mihomo/geo/ipcidr/private-ip.list"
            ["ipcidr/cnip"]="https://github.com/ForestL18/rules-dat/raw/mihomo/asn/combined/China-ASN-combined.list"
            ["ipcidr/telegramip"]="https://github.com/ForestL18/rules-dat/raw/mihomo/asn/combined/Telegram-ASN-combined.list"
            ["ipcidr/googleip"]="https://github.com/ForestL18/rules-dat/raw/mihomo/asn/combined/Google-ASN-combined.list"
          )

          for rule in "${!RULES[@]}"; do
            url="${RULES[$rule]}"
            echo "🔧 Processing: $rule"
            
            if ! curl -sfL -o "${rule}.tmp" "$url"; then
              echo "::error::Download failed: $url"
              exit 1
            fi

            if [[ "$rule" == ipcidr/* ]]; then
            
              mihomo convert-ruleset ipcidr text "${rule}.tmp" "${rule}.mrs"
            else
          
              sed -i '
                /^[[:space:]]*$/d; 
                s/^full://g; 
                s/^DOMAIN-SUFFIX,//g; 
                s/^DOMAIN,//g; 
                s/[[:space:]]*$//g;
              ' "${rule}.tmp"
              
              awk '!seen[tolower($0)]++' "${rule}.tmp" | sort -f > "${rule}.tmp2"
              mihomo convert-ruleset domain text "${rule}.tmp2" "${rule}.mrs"
            fi
            
            rm -f "${rule}.tmp" "${rule}.tmp2"
          done

      - name: Commit Changes
        run: |
          cd src
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add ipcidr/*.mrs domain/*.mrs
          if ! git diff-index --quiet HEAD; then
            git commit -m "chore: Update rules $(date +'%Y-%m-%d %H:%M')" 
            git push origin HEAD:${{ github.ref }}
            echo "✅ Rules updated successfully"
          else
            echo "🟢 No changes detected"
          fi
