name: Rules Converter

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  convert-rules:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: src
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Setup Mihomo
        run: |
          cd src
          curl -sL "https://github.com/MetaCubeX/mihomo/releases/download/v1.19.3/mihomo-linux-amd64-v1.19.3.gz" | gzip -d > mihomo
          chmod +x mihomo && sudo mv mihomo /usr/local/bin/

      - name: Process Rules
        run: |
          cd src
          
          # 定义规则源
          declare -A RULES=(
            ["cdn"]="https://raw.githubusercontent.com/pmkol/easymosdns/rules/cdn_domain_list.txt"
            ["fake_ip"]="https://github.com/juewuy/ShellCrash/raw/dev/public/fake_ip_filter.list"
          )

          for rule in "${!RULES[@]}"; do
            echo "Processing $rule rules..."

            curl -sL "${RULES[$rule]}" -o "${rule}.tmp"
  
            sed -e '/^#/d' -e '/^$/d' "${rule}.tmp" |
            sed -e 's/^full://g' |    
            sort -f > "${rule}.processed"              
            
            mihomo convert-ruleset domain text "${rule}.processed" "${rule}.mrs"
            
            rm "${rule}.tmp" "${rule}.processed"
          done

      - name: Commit Changes
        run: |
          cd src
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add *.mrs
          git diff-index --quiet HEAD || (git commit -m "Update: $(date +'%F')" && git push origin HEAD:${{ github.ref }})
