name: CDN Rules Converter

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点自动运行

jobs:
  convert-rules:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      # 步骤 1: 检出仓库
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: src

      # 步骤 2: 安装指定版本 Mihomo
      - name: Setup Mihomo
        run: |
          cd src
          
          # 使用您提供的下载链接
          MI_URL="https://github.com/MetaCubeX/mihomo/releases/download/v1.19.3/mihomo-linux-amd64-v1.19.3.gz"
          
          # 下载并解压
          curl -sL $MI_URL | gzip -d > mihomo
          
          # 验证并安装
          chmod +x mihomo
          sudo mv mihomo /usr/local/bin/
          mihomo -v  # 验证版本

      # 步骤 3: 哈希比对 (增量更新核心)
      - name: Check Updates
        id: check-updates
        run: |
          cd src
          curl -sL "https://github.com/pmkol/easymosdns/raw/rules/cdn_domain_list.txt" -o raw.txt
          
          CURRENT_HASH=$(sha256sum raw.txt | awk '{print $1}')
          echo "Current hash: $CURRENT_HASH"
          
          if [ -f .last_hash ]; then
            LAST_HASH=$(cat .last_hash)
            echo "Last hash: $LAST_HASH"
          else
            LAST_HASH=""
          fi
          
          if [ "$CURRENT_HASH" != "$LAST_HASH" ]; then
            echo "update_needed=true" >> $GITHUB_OUTPUT
            echo "$CURRENT_HASH" > .last_hash
          else
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi

      # 步骤 4: 生成规则文件
      - name: Generate Rules
        if: steps.check-updates.outputs.update_needed == 'true'
        run: |
          cd src
          grep -vE '^(#|$)' raw.txt |
          sed 's/^\*\.//g' |
          awk '!seen[$0]++' |
          sort -f |
          awk '{print "DOMAIN-SUFFIX,"$0}' > cdn.list
          
          echo -e "# CDN Domain List\n# Updated: $(date -u +'%Y-%m-%dT%H:%M:%SZ')\n# Total: $(grep -c 'DOMAIN-SUFFIX' cdn.list) rules" | cat - cdn.list > temp && mv temp cdn.list
          
          mihomo convert-ruleset \
            --type domain \
            --input cdn.list \
            --output cdn.mrs \
            --compress

      # 步骤 5: 提交变更
      - name: Commit Changes
        if: steps.check-updates.outputs.update_needed == 'true'
        run: |
          cd src
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add cdn.list cdn.mrs .last_hash
          
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Update: $(date +'%Y-%m-%d')"
            git push origin HEAD:${{ github.ref }}
