name: CDN Rules Converter

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点自动运行

jobs:
  convert-rules:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 步骤 1: 检出仓库
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: src

      # 步骤 2: 安装 Mihomo 工具链
      - name: Setup Mihomo
        run: |
          cd src
          MI_URL="https://github.com/MetaCubeX/mihomo/releases/download/v1.19.3/mihomo-linux-amd64-v1.19.3.gz"
          
          # 下载并安装
          curl -sL $MI_URL | gzip -d > mihomo
          chmod +x mihomo
          sudo mv mihomo /usr/local/bin/
          
          # 验证安装
          mihomo -v

      # 步骤 3: 准备目录结构
      - name: Prepare directories
        run: |
          cd src
          mkdir -p {geo/domain,mihomo-rule/geo/domain}

      # 步骤 4: 增量更新检测
      - name: Check Updates
        id: check-updates
        run: |
          cd src
          # 下载最新规则文件
          curl -sL "https://github.com/pmkol/easymosdns/raw/rules/cdn_domain_list.txt" -o raw.txt
          
          # 哈希比对
          CURRENT_HASH=$(sha256sum raw.txt | awk '{print $1}')
          [ -f .last_hash ] && LAST_HASH=$(cat .last_hash) || LAST_HASH=""
          
          if [ "$CURRENT_HASH" != "$LAST_HASH" ]; then
            echo "update_needed=true" >> $GITHUB_OUTPUT
            echo "$CURRENT_HASH" > .last_hash
            
            # 预处理规则文件
            grep -vE '^(#|$)' raw.txt |
            sed 's/^\*\.//g' |
            awk '!seen[$0]++' |
            sort -f |
            awk '{print "DOMAIN-SUFFIX,"$0}' > geo/domain/cdn.list
          else
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi

      # 步骤 5: 转换规则集
      - name: Convert to MRS
        if: steps.check-updates.outputs.update_needed == 'true'
        run: |
          cd src
          # 复制规则文件
          cp geo/domain/*.{list,yaml,yml} mihomo-rule/geo/domain
          
          # 执行转换命令
          mihomo convert-ruleset \
            --behavior domain \
            --input geo/domain \
            --output mihomo-rule/geo/domain \
            --compress
          
          # 重命名输出文件
          mv mihomo-rule/geo/domain/domain.mrs cdn.mrs
          cp geo/domain/cdn.list .

      # 步骤 6: 提交变更
      - name: Commit Changes
        if: steps.check-updates.outputs.update_needed == 'true'
        run: |
          cd src
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # 添加变更文件
          git add cdn.list cdn.mrs .last_hash mihomo-rule/geo/domain/*
          
          # 检测并提交变更
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Update: $(date +'%Y-%m-%d')"
            git push origin HEAD:${{ github.ref }}
          fi
