name: Rules Converter

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  convert-rules:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: src
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Setup Environment
        run: |
          cd src
          mkdir -p {ipcidr,domain}
          sudo apt-get install -y python3-pip
          pip3 install pyyaml
          curl -sfL "https://github.com/MetaCubeX/mihomo/releases/download/v1.19.3/mihomo-linux-amd64-v1.19.3.gz" | gzip -d > mihomo
          chmod +x mihomo && sudo mv mihomo /usr/local/bin/

      - name: Process Rules
        run: |
          cd src
          
          declare -A RULES=(
            ["domain/cdn"]="https://github.com/pmkol/easymosdns/raw/rules/cdn_domain_list.txt"
            ["domain/ai"]="https://github.com/DustinWin/ruleset_geodata/raw/mihomo-ruleset/ai.list"
            ["domain/cn"]="https://github.com/DustinWin/ruleset_geodata/raw/mihomo-ruleset/cn.list"
            ["domain/fake_ip"]="https://github.com/juewuy/ShellCrash/raw/dev/public/fake_ip_filter.list"
            ["domain/private"]="https://github.com/ForestL18/rules-dat/raw/mihomo/geo/domain/private-domain.list"
            ["domain/paypal"]="https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/paypal.yaml"
            ["ipcidr/privateip"]="https://github.com/ForestL18/rules-dat/raw/mihomo/geo/ipcidr/private-ip.list"
            ["ipcidr/cnip"]="https://github.com/ForestL18/rules-dat/raw/mihomo/asn/combined/China-ASN-combined.list"
            ["ipcidr/telegramip"]="https://github.com/ForestL18/rules-dat/raw/mihomo/asn/combined/Telegram-ASN-combined.list"
            ["ipcidr/googleip"]="https://github.com/ForestL18/rules-dat/raw/mihomo/asn/combined/Google-ASN-combined.list"
          )

          for rule in "${!RULES[@]}"; do
            url="${RULES[$rule]}"
            echo "🔄 Processing: $rule"

            # 下载与预处理
            if ! curl -sfL -o "${rule}.origin" "$url"; then
              echo "::error::Download failed: $url"
              exit 1
            fi

            # YAML 格式特殊处理
            if [[ "$url" == *.yaml ]]; then
              python3 -c "import yaml,sys; print('\n'.join(yaml.safe_load(open('${rule}.origin'))['payload']))" > "${rule}.tmp"
              rm "${rule}.origin"
            else
              mv "${rule}.origin" "${rule}.tmp"
            fi

            # 分类处理
            if [[ "$rule" == ipcidr/* ]]; then
              mihomo convert-ruleset ipcidr text "${rule}.tmp" "${rule}.mrs"
            else
              # 域名规则增强处理
              sed -i '
                # 基础清理
                /^[[:space:]]*$/d;      # 删除空行
                s/[[:space:]]*$//g;     # 删除行尾空格

                # 移除策略前缀（保留通配符）
                s/^full://g;            # 移除 full: 前缀
                s/^DOMAIN-SUFFIX,//g;   # 移除 DOMAIN-SUFFIX, 前缀
                s/^DOMAIN,//g;          # 移除 DOMAIN, 前缀

                # 保留原始通配符格式
                # 不修改 +.、*. 和 . 前缀
                
                # 格式验证（允许三种通配符）
                /^(\+\.|\*\.|\.)?[a-zA-Z0-9.-]+$/!d
              ' "${rule}.tmp"

              # 去重排序（保留原始格式）
              awk '!seen[tolower($0)]++' "${rule}.tmp" | sort -f > "${rule}.processed"
              mihomo convert-ruleset domain text "${rule}.processed" "${rule}.mrs"
            fi

            # 清理临时文件
            rm -f "${rule}.tmp" "${rule}.processed"
          done

      - name: Commit Changes
        run: |
          cd src
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ipcidr/*.mrs domain/*.mrs
          if ! git diff-index --quiet HEAD; then
            git commit -m "chore: Update rules $(date +'%Y-%m-%d %H:%M')" 
            git push origin HEAD:${{ github.ref }}
          fi
